#!/bin/bash

source beauty

wrap='\n'
text='str abc'${wrap}'abc   str'${wrap}'str'${wrap}'abc'${wrap}'str'

# 词频统计
echo -e "${text}" | tr -s ' ' '\n' | sort | uniq -c | sort -r | awk '{print $2, $1}'
separate

time=$(date +"%Y-%m-%d %H:%M:%S")
ips=${time}' 127.0.0.1'${wrap}${time}' 127.0.0.2'${wrap}${time}' 127.0.0.1'${wrap}${time}' 127.0.0.2'${wrap}${time}' 127.0.0.3'${wrap}${time}' 127.0.0.2'
# ip访问量前2
echo -e "${ips}"
separate

echo -e "${ips}" | awk '{print $3}' | sort | uniq -c | sort -r | awk '{print $2}' | head -2
separate


